### ISSUE TITLE
A Question of Px2Rem

### ISSUE THREAD

**Issue by joenix** [pedroborges/kirby-boilerplate#1]
Excuse...but Do u know, how px2rem in mix?

**Comment by pedroborges** [comment]
`px2rem` have a PostCSS plugin. So you can just install it: `npm install postcss-px2rem`

Then just add it to `webpack.mix.js`:

```diff
// ...

mix.js('resources/js/main.js', 'public/js')
   .sass('resources/sass/main.scss', 'public/css')
   .options({
     postCss: [
+      require('postcss-px2rem')({remUnit: 64}), // change the size to whatever you want to
       require('postcss-import'),
       require('postcss-css-variables'),
       require('postcss-conditionals'),
       require('postcss-custom-media'),
       require('css-mqpacker'),
       require('autoprefixer')
     ]
   })
```

More info: <https://github.com/JeffreyWay/laravel-mix/issues/439>

I haven't tried this myself, so please let me know if it works.

**Comment by joenix** [comment]
tks, i've fixed this question... a foolish mistake...px2rem...i write rem -.-b...
